application: eduversit
version: 1
runtime: python27
api_version: 1
threadsafe: false

env_variables:
  GCB_PRODUCT_VERSION: '1.5.1'
  gcb_can_share_student_profile: true

inbound_services:
- warmup

builtins:
- remote_api: on
- deferred: on

libraries:
- name: jinja2
  version: "2.6"
- name: webapp2
  version: "2.5.2"
- name: webob
  version: "1.2.3"

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  secure: always
- url: /cron/.*
  script: main.app
  login: admin
  secure: always
- url: /
  upload: index.html
  static_files: index.html
- url: /terms.html
  upload: terms.html
  static_files: terms.html
- url: /robots.txt
  upload: robots.txt
  static_files: robots.txt
- url: /humans.txt
  upload: humans.txt
  static_files: humans.txt
- url: /favicon.ico
  upload: /assets/img/favicon.ico
  static_files: /assets/img/favicon.ico
- url: /.*
  script: main.app
  secure: always